name: Terraform Destroy FULL

on:
  workflow_dispatch:

jobs:

  terraform-destroy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Credentials for AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./Infrastructure-terra
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./Infrastructure-terra
        run: |
          terraform destroy \
          --auto-approve \
          -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -var="code_server_password=${{ secrets.CODE_SERVER_PASSWORD }}" \
          -var="image_id=592587463331.dkr.ecr.eu-north-1.amazonaws.com/code-server-terra:v1"  